doc: update publicKey
was changed in code, but not documentation

lead to error:
error: The option `services.trustix.publishers.[definition 1-entry 1].publicKey.pub' does not exist.